### ISSUE TITLE
博客内有关aria2 的引用链接无效

### ISSUE THREAD

**Issue by gears233** [fanhongtao/fanhongtao.github.com#1]
http://fanhongtao.github.io/2018/12/06/using-aria2.html

文章内容应该是 参考了：https://www.mivm.cn/windows-aria2 吧，不过页面里面引用的有关aria2 的文件是被禁止外链的，显示的是 403 forbidden，作者有空的话把文件更新到 github 内引用吧，不然其他人看到了也无法下载。

**Comment by fanhongtao** [comment]
谢谢你的提醒，已经修改成本地资源。
